
;
; mysql or sqlite (driver)
;
; if sqlite (local storage), no need of host, user and pass
;

"@db_driver"        "sqlite"
"@db_host"          ""
"@db_user"          ""
"@db_pass"          ""
"@db_name"          "dod_hacks_rank"

;
; "1" => rank bots (bots will be ranked)
;
; "0" => do not rank the bots
;        (bots will not be able to appear in top players list/ menu)
;

"@rank_bots"        "1"

;
; "1" => use new special formula: player performance index = (kills + score) / deaths
; "0" => use rusty kdr formula:   player performance index =  kills          / deaths
;

"@use_special"      "1"

;
; "0" => a death will only appear when a player has been
;        killed by a player (not by accident or team change)
;
; "1" => if a player has died, a death should always appear
;
; in this setting, the scores table is not affected or included
;

"@use_classic"      "0"

;
; "1" => if a player dies by accident or team change,
;        the death from the scores table will get erased
;
; "0" => do not change anything
;
; (scores table only, ranking [top, ...] is not affected)
;

"@alter_deaths"     "1"

;
; "1" => rank by steam
; "0" => rank by name
;
; warning: there are 2 db. tables, 1 for name and 1 for steam;
; by changing this setting at a later time, recorded players
; will have to start from scratch
;
; yes, changing at a later time is still possible, without
; having to delete any file from the server
;
; there is only 1 database which holds both name and/ or
; steam tables (if sqlite local storage = only a file on
; the disk)
;
; warning: if using "0" (by name), a player from the server
; may ruin other player's rank by using their name temporarily
; (if not already password protected), increasing their deaths
; counter excessively and therefore destroying their kdr or prf
;

"@rank_steam"       "1"

;
; "0" => players are always ranked (and setting below is ignored)
; "1" => players are ranked only when there are enough playing players
;

"@rank_min_players" "0"

;
; "#" => a min. number of required playing players to allow
; everyone to be ranked on the server
;

"@rank_players_num" "4"

;
; "1" => min. players related, but only humans are counted
; "0" => min. players related, but everyone is counted (including fake players)
;

"@only_humans"      "1"

;
; "1" => show player a welcome message with their rank
; "0" => off
;

"@show_welcome"     "1"

;
; "#" => if the setting above is enabled, after how many seconds after
;        joining the welcome message should be displayed to the player
;

"@task_delay"       "7.5"

;
; "1" => /rank, /top, ... are hidden from chat
; "0" => are displayed
;

"@hide_chat_cmds"   "1"

;
; "0" => do not delete old rank entries
; "1" => old rank entries will be erased during map change
;

"@erase_old"        "0"

;
; "#" => only erase old rank entries older than this amount of
;        seconds
;
; "94670856" = 3 years (def.)
; "63113904" = 2 years
; "31556952" = 1 year
;
; "15778476" = 6 months
;  "7889238" = 3 months
;

"@erase_old_secs"   "94670856"
