
;
; m_flRestartTime (0x1C or 28 at the moment)
;
; offset (to be set as decimal, not hex)
;
; float ::CDoDTeamPlay::m_flRestartTime
;

"@m_flRestartTime"          "28"

;
; seconds adjustment at round end
; (how fast to end a round after
; a team went victorious)
;
; game's default is exactly 3.0 seconds
;
; set here a value of "0.0" to disable
; this plugin entirely
;
; you can use here values from "-2.8"
; seconds ... up to whatever you want
; (i.e. "2.5", "3.0", "9.0", "15.0",
; ...)
;
; using a negative value will help
; end the round faster
;
; using a positive value will help
; prolong the round end event in
; order to help with the hud msg.
; time (so players can understand
; what they read)
;
; def "3.0" -> which means (+3.0 sec.)
;

"@roundEndTimeAdjusSeconds" "3.0"
