
; vertical message position (0.0 <-> 1.0)

"@hud_ver_pos"      "0.2"

; horizontal message position (0.0 <-> 1.0) or -1.0 (screen center)

"@hud_hor_pos"      "-1.0"

; message style (effects) enabled or disabled

"@hud_style"        "0"

; when a player joins, start showing them messages by using
; a random initial position or start from scratch
;
; "1" means random position and "0" means from scratch

"@hud_random"       "1"

; message hold time in seconds

"@hud_hold"         "6.0"

; whether to print the hud message in player's console as well

"@hud_console"      "1"

; should the player see another hud message if the current hud
; message into the shower is dedicated only for admins
;
; "0" for yes and "1" for no

"@hud_pause"        "0"

; seconds interval between two messages

"@task_interval"    "180.0"

; infinite mp_timelimit ('%T%' symbol below)
;
; in case of infinite mp_timelimit (mp_timelimit 0)
; or if mp_timelimit does not exist on this server
; display the following message where applicable
; (where %T% is specified)
;
; good examples are "this round" or "never"
;
; "never" is only if you are running a server that
; doesn't change its map

"@msg_infinite"     "this round"

; messages to be displayed
;
; \n    - new line
; %Q%   - double quote (" symbol)
; %H%   - server name, stripped from unprintable symbols/ characters
; %M%   - map name (with prefix, lowercase)
; %F%   - friendly fire (on/ off, lowercase) [if mp_friendlyfire doesn't exist on the server, off is displayed instead '%F%']
; %T%   - minutes or seconds remaining before map change (lowercase [i.e. 99m, 3m, 5s, ...], see "@msg_infinite" option above)
;
; left side: required admin flag(s) for the message to be seen (or empty flags to show the message to everyone)

""      "To use on-impact nades: type instanades"
""      "Welcome to: %H%"
""      "Console command: bind p nominate"
""      "You're playing on: %M%"
""      "To use a custom gun: type guns"
""      "Auto-medic: on"
""      "On-impact nades: bind mouse4 instanades"
""      "Time remaining: %T%"
""      "To nominate a map: type nominate"
""      "Console command: bind mouse5 +teamvoice"
""      "To change a map sooner: type rtv"
"becl"  "Operator's phone: +8..."
""      "Console command: bind mouse4 instanades"
""      "Join us at: www.google.com"
""      "Chat cmds: guns instanades nominate rtv"
""      "The server is using: AMX Mod X"
""      "Console command: bind o rtv"
""      "To nominate a map: type its name"
""      "Friendly-fire: %F%"
""      "Server hosted by: Provider..."
"d"     "Our Telegram: www..."
""      "Console command: bind i guns"
