
;
; set a title for the menu
;

"@menu_title_british"   "Main Gun (British vs. Axis)"
"@menu_title_allies"    "Main Gun (Allies vs. Axis)"

;
; allow all weapons on all maps
;
; if "1", british players will be able to use british+allies guns
; and allies players will be able to use allies+british guns
; however, when a british player uses an allies gun or
; when an allies player uses a british gun, their arm skin
; will not appear on the screen anymore
; at the moment, this can't be fixed
;
; if "0", only british+axis weapons will be availble on british maps
; and only allies+axis weapons will be available on allies maps
; in this case, there will be no visual bugs at all
;

"@allow_all"    "1"

;
; mysql or sqlite (driver)
;
; if sqlite (local storage), no need of host, user and pass
;

"@db_driver"    "sqlite"
"@db_host"      ""
"@db_user"      ""
"@db_pass"      ""
"@db_name"      "dod_hacks"

;
; secondary weapons ammo to give at spawn (-1 or 0 to not alter default game value)
;
; colt: 210 bullets will display 30 clips (7[per_clip]*30=210)
; luger: 160 bullets will display 20 clips (8[per_clip]*20=160)
; webley: 54 bullets will display 9 clips (6[per_clip]*9=54)
;

"@weapon_colt"      "210"   "ammo_12mm"
"@weapon_luger"     "160"   "ammo_12mm"
"@weapon_webley"    "54"    "ammo_12mm"

;
; grenade(s) to give at spawn (-1 or 0 to not alter default game value)
; for player classes that spawn without a grenade by default
;

"@grenade_allies"   "1"     "weapon_handgrenade"
"@grenade_axis"     "1"     "weapon_stickgrenade"
"@grenade_british"  "1"     "weapon_handgrenade"

;
; 0.0 -> infinity
;
; 15.0 -> if 15.0 seconds elapsed since player spawned, they can still use 'guns' command,
; but their gun selection will only update the next time they spawn
;
; you can specify any value of time you want
;

"@max_seconds"      "0.0"

;
; seconds to wait between two weapon selections
; a protection to avoid spamming the game server
;

"@selection_delay"  "5.0"

;
; if 1, when someone types 'guns' command, it will hide the 'guns' chat message
;

"@hide_chat_cmd"    "1"

;
; add an asterisk (* symbol) as a suffix in weapon names which are admin-only (if any)
;

"@admin_asterisk"   "1"

;
; 1 to delete the dropped gun (if any) when selecting a new one via the menu
;

"@drop_delete"      "1"

;
; how fast to delete the dropped gun (seconds), if "@drop_delete" is set to "1"
; 0.000001 (minimum time) and 5.0 (a value of 5 seconds) [examples]
; game's default value is 20.0 seconds
;

"@delete_time"      "5.0"

;
; whether or not to use a visual effect on the hud message(s)
;
; (i.e. "NO ACCESS!" and "WAIT 2.0 SEC!")
;

"@hud_effects"      "1"

;
; vertical position of the hud message(s)
; (0.0 <-> 1.0)
; use increments/ decrements of 0.05
;
; (i.e. "NO ACCESS!" and "WAIT 2.0 SEC!")
;

"@ver_pos"          "0.35"

;
; horizontal position of the hud message(s)
; (0.0 <-> 1.0) or -1.0 (center of screen)
; use increments/ decrements of 0.05
;
; (i.e. "NO ACCESS!" and "WAIT 2.0 SEC!")
;

"@hor_pos"          "0.0"

;
; make 'guns' command require admin access
; providing multiple flags (a mix of them) is allowed
; use "" to allow everyone in the server use the feature
;

"@admin_access"     ""

;
; require admin access to receive hand gun ammo during spawn
; providing multiple flags (a mix of them) is allowed
; use "" to disable requiring admin access
;

"@handguns_access"  ""

;
; require admin access to receive explosive grenade(s) during spawn
; providing multiple flags (a mix of them) is allowed
; use "" to disable requiring admin access
;

"@nades_access"     ""

;
; weapon entity name    weapon name             weapon team     weapon admin    weapon ammo         weapon ammo amount or -1 (or 0) to not alter default ammo given
;

"weapon_kar"            "Single: KAR"           "A"             ""              "ammo_16mm"         "100"   // 5(per_clip)*20(clips)=100bullets [to display 20 clips]
"weapon_enfield"        "Single: ENFIELD"       "B"             ""              "ammo_16mm"         "100"   // 5(per_clip)*20(clips)=100bullets [to display 20 clips]
"weapon_garand"         "Single: GARAND"        "U"             ""              "ammo_16mm"         "160"   // 8(per_clip)*20(clips)=160bullets [to display 20 clips]

"weapon_k43"            "Semi: K43"             "A"             ""              "ammo_66mm"         "200"   // 10(per_clip)*20(clips)=200bullets [to display 20 clips]
"weapon_m1carbine"      "Semi: M1 CARBINE"      "U"             ""              "ammo_66mm"         "300"   // 15(per_clip)*20(clips)=300bullets [to display 20 clips]

"weapon_fg42"           "Auto: FG42"            "A"             ""              "ammo_55mm"         "400"   // 20(per_clip)*20(clips)=400bullets [to display 20 clips]
"weapon_bar"            "Auto: BAR"             "U"             ""              "ammo_55mm"         "400"   // 20(per_clip)*20(clips)=400bullets [to display 20 clips]
"weapon_bren"           "Auto: BREN"            "B"             ""              "ammo_55mm"         "600"   // 30(per_clip)*20(clips)=600bullets [to display 20 clips]
"weapon_mp44"           "Auto: MP44"            "A"             ""              "ammo_55mm"         "600"   // 30(per_clip)*20(clips)=600bullets [to display 20 clips]
"weapon_mp40"           "Auto: MP40"            "A"             ""              "ammo_44mm"         "600"   // 30(per_clip)*20(clips)=600bullets [to display 20 clips]
"weapon_thompson"       "Auto: THOMPSON"        "U"             ""              "ammo_44mm"         "600"   // 30(per_clip)*20(clips)=600bullets [to display 20 clips]
"weapon_greasegun"      "Auto: GREASEGUN"       "U"             ""              "ammo_44mm"         "600"   // 30(per_clip)*20(clips)=600bullets [to display 20 clips]
"weapon_sten"           "Auto: STEN"            "B"             ""              "ammo_44mm"         "600"   // 30(per_clip)*20(clips)=600bullets [to display 20 clips]

"weapon_scopedfg42"     "Scoped Auto: FG42"     "A"             "b"             "ammo_55mm"         "400"   // 20(per_clip)*20(clips)=400bullets [to display 20 clips]

"weapon_spring"         "Scoped: SPRING"        "U"             ""              "ammo_22mm"         "100"   // 5(per_clip)*20(clips)=100bullets [to display 20 clips]
"weapon_scopedkar"      "Scoped: KAR"           "A"             ""              "ammo_22mm"         "100"   // 5(per_clip)*20(clips)=100bullets [to display 20 clips]
"weapon_scopedenfield"  "Scoped: ENFIELD"       "B"             ""              "ammo_16mm"         "100"   // 5(per_clip)*20(clips)=100bullets [to display 20 clips]

"weapon_mg34"           "MG: MG34"              "A"             ""              "ammo_66mm"         "1500"  // 75(per_clip)*20(clips)=1500bullets [to display 20 clips]
"weapon_mg42"           "MG: MG42"              "A"             "ak"            "ammo_66mm_ger"     "5000"  // 250(per_clip)*20(clips)=5000bullets [to display 20 clips]
"weapon_30cal"          "MG: 30CAL"             "U"             ""              "ammo_66mm_us"      "3000"  // 150(per_clip)*20(clips)=3000bullets [to display 20 clips]

"weapon_piat"           "Rocket: PIAT"          "B"             ""              "rockets"           "9"     // 1(per_clip)*9(clips)=9bullets [to display 9 clips]
"weapon_bazooka"        "Rocket: BAZOOKA"       "U"             ""              "rockets"           "9"     // 1(per_clip)*9(clips)=9bullets [to display 9 clips]
"weapon_pschreck"       "Rocket: PSCHRECK"      "A"             ""              "rockets"           "9"     // 1(per_clip)*9(clips)=9bullets [to display 9 clips]
