
;
; keep & restore fake
; player scores as well?
;
; by score you understand
;
; objective score, kills
; & deaths (not just score)
;
; note: scores are kept
; only for the current map
;
; (not lifetime or
; indefinitely)
;

"@include_fake_players"     "1"
