
;
; maximum explosive grenades a player can carry at a time
;
; minimum value is "2" (to not entirely break the game)
; maximum value is "6"
;

"@max_nades"                "6"

;
; maximum explosive grenades a dead player will drop
;
; if "0" (minimum value), dropping explosive grenades
; on death is fully disabled
;
; maximum value is "6" (as some distance between multiple
; on-death dropped explosive grenades is needed)
;

"@max_drop"                 "6"

;
; second(s) required to erase from map an on-death dropped
; explosive grenade, if not already picked up by a player
;
; game's default value would be "20.0" (i.e. items dropped
; via "drop" console command/ G key)
;

"@sec_removal"              "20.0"

;
; whether or not to delete all on-death dropped explosive
; grenades from map when a new round begins
;

"@del_new_round"            "1"

;
; drop explosive grenades on suicides
; ('kill' console command, slay and slap)
;
; "1" means yes
;

"@drop_suicide"             "1"

;
; drop explosive grenades on suicides
; (resulted from gun damage or grenades)
;
; "1" means yes
;

"@drop_suicidegun"          "1"

;
; whether or not to drop explosive grenades on accidental
; deaths (i.e. fall damage)
;

"@drop_accidental"          "1"

;
; whether or not to drop explosive grenades on accidental
; deaths when changing the team while alive
;

"@drop_tchange"             "1"

;
; whether or not to drop explosive grenades on deaths caused by
; map entities (i.e. ai-driven enemy territory machine guns)
;

"@drop_ents"                "1"

;
; whether or not to drop explosive grenades on friendly
; fire incidents
;

"@drop_friendly_fire"       "1"

;
; whether or not to drop explosive grenades on explosive
; related deaths (i.e. player was killed by a rocket launcher,
; mortar or hand grenade)
;

"@drop_explo"               "1"

;
; wait x second(s) after a player spawns
; (to drop explo. nades on player death)
;
; if not enough second(s) elapsed since
; player spawned and they die, no explo.
; nades will be dropped this time
;

"@drop_seconds"             "20.0"

;
; whether or not to show hud message(s) when picking up an
; on-death dropped explosive grenade
;
; (i.e. "+1 EXPLO NADE!")
;

"@hud_msg"                  "1"

;
; whether or not to use a visual effect on the hud message(s)
;
; (i.e. "+1 EXPLO NADE!")
;

"@hud_effects"              "0"

;
; vertical position of the hud message(s)
; use increments/ decrements of 0.05
; (0.00 <-> 1.00)
;
; (i.e. "+1 EXPLO NADE!")
;

"@ver_pos"                  "0.55"

;
; horizontal position of the hud message(s)
; use increments/ decrements of 0.05
; (0.00 <-> 1.00) or -1.0 (screen center)
;
; (i.e. "+1 EXPLO NADE!")
;

"@hor_pos"                  "1.0"

;
; enable or disable on-impact explosive grenade projectile
; detonations client command/ feature
;
; disabling this command disables the entire feature
;
; "0" disabled
; "1" enabled
;

"@on_impact"                "1"

;
; you only need to configure these if you are planning to use
; the "on-impact explosive grenade projectile detonations"
; feature (see above)
;
; mysql or sqlite (driver)
;
; if sqlite (local storage), no need of host, user and pass
;

"@db_driver"                "sqlite"
"@db_host"                  ""
"@db_user"                  ""
"@db_pass"                  ""
"@db_name"                  "dod_hacks"

;
; show a hud message when an explosive grenade is being
; thrown and the player's on-impact detonations setting
; is turned on
;
; (i.e. "IMPACT DETONATION!")
;

"@msg_impact"               "1"

;
; vertical position of the message
; use increments/ decrements of 0.05
; (0.00 <-> 1.00)
;
; (i.e. "IMPACT DETONATION!")
;

"@ver_pos_impact"           "0.75"

;
; horizontal position of the message
; use increments/ decrements of 0.05
; (0.00 <-> 1.00) or -1.0 (center of screen)
;
; (i.e. "IMPACT DETONATION!")
;

"@hor_pos_impact"           "1.0"

;
; whether or not to use a visual effect on the hud message
;
; (i.e. "IMPACT DETONATION!")
;

"@hud_effects_impact"       "1"

;
; vertical position of the message(s) (when calling the command)
; use increments/ decrements of 0.05
; (0.00 <-> 1.00)
;
; (i.e. "IMPACT DETONATION ON!" or "IMPACT DETONATION OFF!")
;

"@ver_pos_impact_cmd"       "0.3"

;
; horizontal position of the message(s) (when calling the command)
; use increments/ decrements of 0.05
; (0.00 <-> 1.00) or -1.0 (screen center)
;
; (i.e. "IMPACT DETONATION ON!" or "IMPACT DETONATION OFF!")
;

"@hor_pos_impact_cmd"       "0.0"

;
; whether or not to use a visual effect on the hud message(s)
;
; (i.e. "IMPACT DETONATION ON!" or "IMPACT DETONATION OFF!")
;

"@hud_effects_impact_cmd"   "0"

;
; required admin access for the console/ chat command or ""
; to allow all players use the command
;
; can be one flag or more
;

"@cmd_flag"                 "ae"

;
; client console/ chat command name for on-impact detonations
;
; if changing this, manually update cmdaccess.ini file as well
;

"@cmd_name"                 "instanades"

;
; hide when the command is typed in chat
;
; (i.e. instanades, !instanades, /instanades, ,instanades and .instanades)
;
; chat command will be automatically updated if you edit the console command
;

"@hide_chat_cmd"            "1"

;
; whether to force players use their knife if they're
; already using a knife and picking up explo. nades
;

"@force_knife"              "1"

;
; glow explo. grenade projectiles (while in air)
;

"@allow_glow"               "1"

;
; glow dropped explo. grenades (while on ground)
;

"@allow_dropped_glow"       "1"
