
;
; whether to force bots join
; Spectators team if they are
; AFK for a long time
;

"@include_fake_players"     "0"

;
; if a player did not move for
; this long, they'll
; automatically join
; Spectators team
;
; this plugin ignores +left
; or +right commands
;
; min. value "15.0"
; def. value "60.0"
;

"@afk_seconds"              "60.0"

;
; admin flag(s) to use so
; certain players will be
; excluded
;
; i.e. "a", "efg", ...
;

"@admin_flag"               ""
