
;
; ip v4 address of server
;

"@server_ip_v4_address"     "91.200.220.20"

;
; whether to include player distance
; to game server into the chat msgs.
;

"@include_player_distance"  "1"

;
; whether server distances are
; imperial (mi) or metric (km)
;
; "0" => metric
; "1" => imperial
;

"@is_distance_imperial"     "0"

;
; how to declare mi or km symbols
;
; "0" => mi & km
; "1" => Mi & Km
; "2" => MI & KM
;

"@distance_symbol_style"    "1"

;
; whether to turn off game's default
; "#game_joined_game" message
;
; (i.e. "Hattrick joins the game")
;
; since geo. location is now displayed
; within "#game_joined_team" message
;
; (i.e. "Hattrick joins Axis")
;

"@block_def_join_msg"       "1"

;
; "1" => bots will use a fake ip
;        address so the server shows
;        them as they were human players
;
; "0" => bots will never have a valid
;        geographic location
;

"@alter_bots"               "1"
