
;
; interval in second(s) between two team checks
;

"@task_interval"    "0.2"

;
; if "1", it shows a message like
;
; "* Hattrick joined Allies to balance teams."
;
; if "0", it shows the original game message
;
; "*Hattrick joined Allies"
;

"@show_custom_msg"  "1"
