
;
; a - darkest  possible
; z - lightest possible
;
; m - usually game's
;     default
;

;
; a general setting,
; if defined (if wanted)
;

; "@general"            "m"

;
; per-map setting(s)
;

"dod_anzio"             "u"
"dod_zafod2_b5"         "z"
