
;
; min. second(s) to wait before
; starting to notify the
; player about their irregular
; cvar setting(s)
;

"@min_notify_sec"   "30.0"

;
; max. second(s) to wait before
; starting to notify the
; player about their irregular
; cvar setting(s)
;

"@max_notify_sec"   "360.0"
