
;
; second(s) delay between two
; ping update tasks
;
; def "1.0"
;

"@task_interval"            "1.0"

;
; second(s) delay between two
; player ping updates
;
; def "2.0"
;

"@update_interval"          "2.0"

;
; maximum ping (real player)
;
; use a value like 4194304 to
; disable touching/ altering
; real player pings
;
; def "150"
;

"@max_real_ping"            "150"

;
; maximum ping (real player)
; deletion from above value
;
; i.e. "12" would make real
; player ping fluctuate from
; 138 to 150, as 150 - 12 =
; 138
;
; def "12"
;

"@max_real_ping_del"        "12"

;
; minimum fake player
; base ping
;
; def "10"
;

"@min_fake_base_ping"       "10"

;
; maximum fake player
; base ping
;
;; def "90"
;

"@max_fake_base_ping"       "90"

;
; maximum fake player base
; ping deletion (from main
; fake player base ping)
;
; def "6"
;

"@max_fake_base_ping_del"   "6"

;
; maximum fake player base
; ping addition (to main
; fake player base ping)
;
; def "6"
;

"@max_fake_base_ping_add"   "6"
