
; beam life (i.e. "10" means 1 second)

"@life"     "20"

; beam width

"@width"    "8"

; beam noise amplitude or 0 for no noise at all

"@noise"    "0"

; beam scroll speed or 0 for no scroll at all

"@scroll"   "0"

; red (allies)

"@r_allies" "20"

; green (allies)

"@g_allies" "180"

; blue (allies)

"@b_allies" "120"

; brightness/ alpha (allies)

"@a_allies" "200"

; red (axis)

"@r_axis"   "200"

; green (axis)

"@g_axis"   "20"

; blue (axis)

"@b_axis"   "20"

; brightness/ alpha (axis)

"@a_axis"   "200"
