
;
; interval between two checks
;

"@task_interval"        "0.1"

;
; minimum value tested  "0.25"
; that would still work well
;

;
; default time needed for respawning players (for all maps [that are not listed below])
;
; note: to disable the general setting and only use per-map setting(s), set the two
; values below as "262144.0"
;

"@def_allies_time"      "0.25"
"@def_axis_time"        "0.25"

;
; per-map setting(s) [if any]
;

; map name              time allies (seconds)       time axis (seconds)

"dod_flash"             "0.25"                      "0.25"
"dod_kalt"              "0.25"                      "0.25"
