
;
; "0" to load all maps from "maps" folder
; "1" to load maps from mapcycle text file (commonly mapcycle.txt)
; "2" to load maps from AMX Mod X maps text file
;
; if "1", "mapcyclefile" console variable will be considered
; before trying to open and read the text file (i.e. mapcycle.txt)
;
; if "2", the file is called "/addons/amxmodx/configs/maps.ini"
; by default, but its path can be changed from AMX Mod X core.ini
;

"@mapchooser_mapcycle"          "0"

;
; exclude from vote if no '/maps/%map%.res' file
;
; note: use a resgen (resources list generator) to
; generate resources for all maps, even for DoD
; default ones (as they come with no .res files)
;
; or, turn this feature off (set it to "0")
;

"@mapchooser_exclres"           "1"

;
; exclude from vote if no '/shrikebot/waypoints/%map%.wps' file
;

"@mapchooser_exclshrike"        "1"

;
; exclude from vote if no '/sturmbot/waypoints/%map%.wpt' file
;

"@mapchooser_exclsturm"         "0"

;
; exclude from vote if no '/marinebot/defaultwpts/%map%.wpt' file
;

"@mapchooser_exclmarinewpt"     "0"

;
; exclude from vote if no '/marinebot/defaultwpts/%map%.pth' file
;

"@mapchooser_exclmarinepth"     "0"

;
; exclude from vote if no '/overviews/%map%.bmp' file
;

"@mapchooser_exclovbmp"         "1"

;
; exclude from vote if no '/overviews/%map%.txt' file
;

"@mapchooser_exclovtxt"         "1"

;
; if decided to extend the actual map, for
; how many minute(s) will it be extended
;
; minimum value is "1.0"
;

"@mapchooser_extstep"           "15.0"

;
; do not start the end-of-map vote earlier than this
; number of remaining seconds before map change
;
; minimum value is "60.0"
;
; "180.0" is not a good idea because two voices will mix
; on a default AMX Mod X installation (i.e. "THREE MINUTES
; REMAINING" + "GET READY TO CHOOSE A MAP")
;

"@mapchooser_seconds"           "150.0"

;
; "amx_nextmap" console variable will be
; set to this when the actual map begins
;
; this string must not represent a map
; name and should never be empty
;
; a good secondary option would be
; "[not yet voted on]"
;

"@mapchooser_tbdname"           "[to be decided]"

;
; end-of-map vote duration in seconds
;
; it's recommended to use values
; like 10.0, 15.0, 20.0, 25.0, 30.0 and 35.0
; for the best experience
; (so choose a number ending with ".0")
;
; you can use a value like "19.0" but
; "19.5" or "19.9" isn't recommended
; (as hud message(s) won't properly sync)
;
; minimum value is "10.0"
; maximum value is "35.0"
;

"@mapchooser_duration"          "23.0"

;
; show an initial grey menu before the
; real end-of-map vote menu ("1" if yes)
;

"@mapchooser_greymenu"          "1"

;
; grey menu duration in second(s)
;
; while the players initially see
; this grey menu of maps, they
; can't vote a map yet
;
; minimum "1.0"
; maximum "5.0"
;

"@mapchooser_greymenuduration"  "3.0"

;
; if you choose to use a grey menu
; the total end-of-map vote duration
; will still be "@mapchooser_duration"
;
; and not "@mapchooser_duration" +
; "@mapchooser_greymenuduration"
;

;
; extension item suffix for the end-of-map vote menu
;
; \y = yellow (creator's default)
; \w = white  (game's    default)
; \r = red
; \d = grey
;
; if no color key is specified, \w will be used
;
; the space between the map name and the suffix
; is automatically added and shouldn't be
; provided here
;

"@mapchooser_extsuffix"         "\y(EXTEND)"

;
; "" to allow everyone nominate and denominate maps
; use a flag or more to restrict access to admins only
;
; for example, "a" or "becd"
;

"@mapchooser_nomflags"          ""

;
; "" to allow everyone rock the vote
; use a flag or more to restrict access to admins only
;
; for example, "a" or "becd"
;

"@mapchooser_rockflags"         ""

;
; how many maps will be included into the end-of-map vote menu,
; excepting the actual one (which is the extension option)
;
; maximum value is "8"
; minimum value is "0"
;

"@mapchooser_desiredmaps"       "8"

;
; skip actual map from appearing into the end-of-map vote menu
; this doesn't affect the actual map extension feature
;

"@mapchooser_skipactual"        "1"

;
; include hud message before the decision menu appears
;
; (i.e. "GET READY TO VOTE!")
;

"@mapchooser_hudmsgdecision"    "1"

;
; include hud messages to be displayed as a countdown
; timer until the end-of-map vote ends
;
; (i.e. "12 SEC. LEFT!")
;

"@mapchooser_hudmsgtimer"       "1"

;
; hud message(s) vertical position
; (0.0 <-> 1.0)
; increment/ decrement with 0.05
;

"@mapchooser_hudverpos"         "0.35"

;
; hud message(s) horizontal position
; (0.0 <-> 1.0) or -1.0 (screen center)
; increment/ decrement with 0.05
;

"@mapchooser_hudhorpos"         "0.0"

;
; make hud message(s) display with a vibrant effect
;

"@mapchooser_hudstyle"          "0"

;
; block changing "amx_nextmap" console variable
; by anything else than this plugin (if "1")
;
; a value of "0" allows admins change 'amx_nextmap'
; cvar via amx_cvar and amx_rcon console cmds.
;
; this option is useful because if someone changes
; 'amx_nextmap' cvar before an end-of-map vote,
; there will be no more vote
;
; if someone changes 'amx_nextmap' after a vote,
; everything will be fine
;
; use "2" to block changing 'amx_nextmap' only
; before a vote took place (being allowed to
; be manually changed by admins afterwards)
;
; the new map will always be checked for validity
;

"@mapchooser_blocknextmap"      "2"

;
; block changing "mp_timelimit" console variable
; by anything else than this plugin
;
; a value of "0" allows admins change 'mp_timelimit'
; cvar via amx_cvar and amx_rcon console cmds.
;

"@mapchooser_blocktimelimit"    "1"

;
; at least x% players should rock the
; vote to start the end-of-map vote
;

"@mapchooser_rockpercent"       "50.000001"

;
; hide chat commands (nominate and rtv)
; when players type them
;
; this also hides dod_anzio, dod_flash, ...
; when typed (to nominate/ denominate them)
;

"@mapchooser_hidechatcmds"      "1"

;
; enable or disable "rock the vote"
; feature entirely
;

"@mapchooser_rockthevote"       "1"

;
; enable or disable "nominations"
; feature entirely
;

"@mapchooser_nominations"       "1"

;
; allow players nominate/ denominate
; maps by typing their names in chat
;

"@mapchooser_mapbychat"         "1"

;
; show a hud message to the player when they nominate or
; denominate a map (a chat message is already displayed to them)
;

"@mapchooser_hudmsgnomination"  "1"

;
; only change the map after the round ends if "1"
;
; if "0", change the map when map time limit ends
;

"@mapchooser_onlyafter"         "0"

;
; if this number of seconds remain till end-of-map
; vote, announce players via a hud message that
; they'll have to vote soon
;
; minimum value is "5"
;

"@mapchooser_secannounce"       "15"

;
; minimum wait time in seconds between the map load time and the
; moment of being able to start using rock the vote feature
;
; minimum value is "60.0"
;

"@mapchooser_rockmapdelay"      "120.0"

;
; this option should only be configured when
; '@mapchooser_blocktimelimit' is set to "0"
;
; if an admin change mp_timelimit during a map,
; the next map (after map change) will still
; need a mp_timelimit value
;
; this option allows you ensure the
; mp_timelimit value for the new map (set by
; an admin on the previous map) is not lower
; than this
;
; this is intended to prevent new maps loading
; with mp_timelimit set to small values like
; 0.02 (6 seconds)
;

"@mapchooser_mintimelimit"      "5.0"

;
; this option should only be configured when
; '@mapchooser_blocktimelimit' is set to "0"
;
; if an admin change mp_timelimit during a map,
; the next map (after map change) will still
; need a mp_timelimit value
;
; this option allows you ensure the
; mp_timelimit value for the new map (set by
; an admin on the previous map) is not higher
; than this
;

"@mapchooser_maxtimelimit"      "720.0"

;
; when actual map ends, load server.cfg
; (considering 'servercfgfile' con. var.)
; and update/ sync new map's mp_timelimit
; con. var. automatically (if "1")
;
; this setting will not cause server.cfg
; to be executed during map changes
;
; map chooser plugin only searches for
; mp_timelimit con. var. to sync it
;
; this plugin makes no changes to
; server.cfg file (only opens it for
; reading)
;

"@mapchooser_loadsvcfg"         "1"
