
;
; whether to allow bots use machine guns
;

"@allowGunners" "0"

;
; whether to allow bots use sniper rifles
;

"@allowSnipers" "0"

;
; whether to allow bots use rocket launchers
;

"@allowRockets" "0"
