
;
; effects into the hud message (1 or 0)
;

"@hud_effects"          "1"

;
; whether or not to perform team check
; to not display "HEAD!" hud message on
; team attack
;

"@team_check"           "0"

;
; hud message vertical position on the screen (0.0 <-> 1.0)
;
; use increments/ decrements of 0.05
;

"@hud_vertical_pos"     "0.7"

;
; hud message horizontal position on the screen (0.0 <-> 1.0)
;
; -1.0 for screen center
;
; use increments/ decrements of 0.05
;

"@hud_horizontal_pos"   "1.0"
