
;
; corpses frame rate #1
;
; 'float ::entvars_s::framerate'
; to use during PlayerDeathThink()
; calls when
; 'float ::entvars_s::framerate'
; > 0.0 already
;
; game's   default: "1.0"
; plugin's default: "2.0"
;

"@PevFrameRate"         "2.0"

;
; corpses frame rate #2
;
; 'float ::CBasePlayer::m_flFrameRate'
; to use during PlayerDeathThink()
; calls (unconditioned)
;
; game's   default: "0.0" (on Windows)
; game's   default: "???" (on Linux)
;
; plugin's default: "0.0"
;

"@CBaseFrameRate"       "0.0"

;
; corpses think speed reduction
;
; (on each frame)
;
; value to subtract from
; 'float ::CBasePlayer::m_iRespawnFrames'
; on each PlayerDeathThink() call when
; 'float ::CBasePlayer::m_iRespawnFrames'
; > 0.0 already
;
; game's   default: "0.0"
; plugin's default: "1.0"
;

"@RespawnFramesSub"     "1.0"

;
; whether to alter "@CBaseFrameRate"
;
; (as seen above)
;
; whether to alter
; 'float ::CBasePlayer::m_flFrameRate'
; during PlayerDeathThink() calls
; (unconditioned)
;
; "1" => alter, using value above
;        (on every death frame)
;
; "0" => do not touch
;        'float ::CBasePlayer::m_flFrameRate'
;        at all
;
; game's   default: "0"
; plugin's default: "0"
;

"@AlterCBaseFrameRate"  "0"

;
; whether to enable
; corpses interpolation
;
; whether to remove EF_NOINTERP
; effect from
; 'int ::entvars_s::effects'
; during PlayerDeathThink()
; calls
;
; game's   default: "0"
; plugin's default: "0"
;

"@EnableInterp"         "0"
