
;
; effects into the hud message (1 or 0)
;

"@hud_effects"          "0"

;
; whether hud message is director style or classic hud sync
;

"@hud_director"         "1"

;
; hud message vertical position on the screen (0.0 <-> 1.0)
;
; use increments/ decrements of 0.05
;

"@hud_vertical_pos"     "1.0"

;
; hud message horizontal position on the screen (0.0 <-> 1.0)
;
; -1.0 for screen center
;
; use increments/ decrements of 0.05
;

"@hud_horizontal_pos"   "0.7"
