
;
; throwing knives speed in units/ s
; default "1600"
;

"@speed"                    "1600"

;
; units to add in throwing knives vertical
; position (origin) when they spawn
; default "8.0"
;

"@offs"                     "8.0"

;
; spade pitch angle offset to add
; (to adjust its model direction)
; default "-35.0"
;

"@spade_x_angle_offs"       "-35.0"

;
; gerknife pitch angle offset to add
; (to adjust its model direction)
; default "50.0"
;

"@gerknife_x_angle_offs"    "50.0"

;
; amerknife pitch angle offset to add
; (to adjust its model direction)
; default "30.0"
;

"@amerknife_x_angle_offs"   "30.0"

;
; whether to allow players
; attack teammates
;

"@allow_team_attack"        "0"

;
; damage to breakables and players
;

"@damage_knife"             "120.0"

;
; damage to players if they are
; hit at the legs
;

"@damage_knife_low"         "80.0"

;
; whether to allow infinite attacks
;

"@infinite_attacks"         "0"

;
; whether to allow infinite attempts
;

"@infinite_attempts"        "1"
