
;
; if a player is AFK +
; spectator for this long
; and server is full of
; players at the same time
; they'll be kicked out
; from the server
;
; min. value "15.0"
; def. value "30.0"
;

"@spec_seconds"     "30.0"

;
; admin flag(s) to use so
; certain players will be
; excluded
;
; i.e. "a", "efg", ...
;

"@admin_flag"       ""
