
;
; interval in second(s) between two team checks
;

"@task_interval"    "0.2"

;
; if "1", it shows a message like
;
; "* Hattrick joined Allies to balance teams."
;
; if "0", it shows the original game message
;
; "*Hattrick joined Allies"
;

"@show_custom_msg"  "1"

;
; if "1", will show a screen fade to the
; player once transferred
;

"@show_screen_fade" "1"

;
; if "1", will play an audio beep
; to the player once transferred
;

"@audio_beep"       "1"

;
; admin flag(s) that will exclude a player
; from being transferred (if any)
;
; optional, can be "a", "cdkl", ..
;

"@excl_flags"       ""

;
; if "1", players that have not selected
; a class yet will be excluded from transfer
;
; yes, a player can select a team, but they
; won't spawn until they have fully selected
; a class or a random class
;
; if "1", such players will
; not be transferred
;

"@excl_unclassed"   "1"
