
;
; DoD ScreenFade messages
; can be sent with a
; brightness up to 255 (max)
;
; DoD will send ScreenFade
; messages with a brightness
; up to "#" (see/ set below)
;
; max. allowed: "254"
; min. allowed: "0"
;
; do not use "255" here
; disable the plugin instead
;

"@max_brightness"   "150"
