
;
; OFFSDEC: 484              (offset, dec)
; SIG: FF 04 * 32 ? 89      (sig, * and ? allow zero)
; SIG: FF                   (byte)
; OFFSHEX: 2C               (offset, hex)
; _Z16InstallGameRulesv     (sym, linux)
; ?Kill@CWeaponBox@@QAEXXZ  (sym, windows)
;

/////////
[WINDOWS]
/////////

///////////////////////////////////////// Signatures (__thiscall funcs.) ////////////////////////////////////////////////////////////////////////

; CDoDTeamPlay::PlayerSpawn
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 83 ? ? ? ? ? ? 74 ? E9 ? ? ? ? 8B ? ? 8B ? ? 83 ? ? ? ? ? ? 74 ? E9 ? ? ? ? 8B ? ? 8B ? ? 83 ? ? ? ? ? ? 74 ? 8B

; CBasePlayer::GiveNamedItem
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 99 8B ? 8B ? 8B ? ? ? ? ? 8B ? ? ? ? ? 99 2B ? 1B ? 89 ? ? 8B ? ? 50 E8 ? ? ? ? 83

; CBasePlayer::DropPlayerItem
SIG: 55 8B ? 81 ? ? ? ? ? 53 56 57 89 ? ? 8B ? ? 50 E8 ? ? ? ? 83 ? ? 85 ? 75 ? C7 ? ? ? ? ? ? 83 ? ? ? 74 ? 68 ? ? ? ? 8B ? ? 50 E8

; CBasePlayer::GiveAmmo
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 83 ? ? ? 75 ? 83 ? ? E9 ? ? ? ? 8B ? ? 50 8B ? ? 51 8B ? ? 52 A1

; CDoDTeamPlay::SetWaveTime
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 50 8B ? ? E8 ? ? ? ? 33 ? 8A ? 85 ? 75 ? E9 ? ? ? ? 8B ? ? 89 ? ? 83

; CDoDTeamPlay::GetWaveTime
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 89 ? ? 83 ? ? ? 74 ? 83 ? ? ? 74 ? EB ? 8B ? ? 8B ? ? ? ? ? D9

; CBasePlayer::RemovePlayerItem
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 8B ? ? ? ? ? 3B ? ? 75 ? 6A ? 8B ? ? 8B ? 8B ? ? FF

; CBasePlayer::AddPlayerItem
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 8B ? 8B ? ? FF ? ? ? ? ? 8B ? ? 8B ? ? ? ? ? ? 89 ? ? 83 ? ? ? 0F

; CBasePlayer::RemoveAllItems
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 83 ? ? ? ? ? ? 74 ? 6A ? 8B ? ? 8B ? ? ? ? ? 8B ? ? 8B ? ? ? ? ? 8B ? 8B ? FF ? ? ? ? ? 8B ? ? C7

; CBaseAnimating::SetBodygroup
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? 8B ? ? 50 8B ? ? 51 8B ? ? 8B ? ? 50 8B ? ? 8B ? ? 52 E8

; CBasePlayerItem::DestroyItem
?DestroyItem@CBasePlayerItem@@QAEXXZ

; CBaseEntity::SUB_Remove
?SUB_Remove@CBaseEntity@@QAEXXZ

; CWeaponBox::PackWeapon
SIG: 55 8B ? 81 ? ? ? ? ? 53 56 57 89 ? ? 8B ? ? 50 8B ? ? E8 ? ? ? ? 85 ? 74 ? 33 ? E9

; CWeaponBox::Kill
?Kill@CWeaponBox@@QAEXXZ

; CWeaponBox::ActivateThink
?ActivateThink@CWeaponBox@@QAEXXZ

; CDoDTeamPlay::ChangePlayerTeam
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? C7 ? ? ? ? ? ? 8B ? ? E8 ? ? ? ? 89 ? ? 8B ? ? C1 ? ? 05 ? ? ? ? 89

; CDoDTeamPlay::ChooseRandomClass
SIG: 55 8B ? 83 ? ? 53 56 57 89 ? ? C7 ? ? ? ? ? ? C7 ? ? ? ? ? ? C7 ? ? ? ? ? ? 8B ? ? 8B ? ? 83 ? ? ? ? ? ? 75 ? 8B

///////////////////////////////////////// Signatures (__cdecl funcs.) ////////////////////////////////////////////////////////////////////////

; CBaseEntity::Create
SIG: 55 8B ? 83 ? ? 53 56 57 8B ? ? 99 8B ? 8B ? 8B ? ? ? ? ? 8B ? ? ? ? ? 99 2B ? 1B ? 51 E8 ? ? ? ? 83 ? ? 89 ? ? 8B ? ? 50 E8 ? ? ? ? 83 ? ? 85 ? 74 ? 68 ? ? ? ? 6A ? FF ? ? ? ? ? 83 ? ? 33 ? EB ? 8B

; InstallGameRules
SIG: 55 8B ? 83 ? ? 53 56 57 68 ? ? ? ? FF ? ? ? ? ? 83 ? ? FF ? ? ? ? ? C7

; UTIL_Remove
SIG: 55 8B ? 83 ? ? 53 56 57 83 ? ? ? 75 ? EB ? 8B ? ? E8 ? ? ? ? 8B ? ? 8B ? ? 8B

; CREATE_NAMED_ENTITY
SIG: 55 8B ? 83 ? ? 53 56 57 8B ? ? 50 FF ? ? ? ? ? 83 ? ? 89 ? ? 8B ? ? 50 E8

; SV_CalcPing (new swds.dll)
SIG: 55 8B ? 56 8B ? ? 83 ? ? ? ? ? ? 75 ? A1 ? ? ? ? 33 ? 99 0F ? ? 2B ? 0F ? ? 8B ? D1 ? 83 ? ? 7D ? 85 ? 7F

; SV_CalcPing (old swds.dll)
SIG: 55 8B ? 51 8B ? ? 56 33 ? 39 ? ? ? ? ? 74 ? 33 ? 5E 8B ? 5D C3 A1

; SV_CalcPing (rehlds swds.dll) [ReHLDS Windows: This Engine function is `__thiscall'.]
SIG: 55 8B ? 83 ? ? 56 57 8B ? 83 ? ? ? ? ? ? 0F ? ? ? ? ? A1 ? ? ? ? 83 ? ? 7F ? 99 2B ? 8B ? D1 ? 85 ? 0F ? ? ? ? ? EB ? BE

; Host_Ping_f (new swds.dll)
SIG: 83 ? ? ? ? ? ? 0F ? ? ? ? ? 56 57 68 ? ? ? ? E8 ? ? ? ? A1 ? ? ? ? 83 ? ? 8B

; Host_Ping_f (old swds.dll)
SIG: A1 ? ? ? ? 56 83 ? ? 57 75 ? 5F 5E E9 ? ? ? ? 68

; Host_Ping_f (rehlds swds.dll)
SIG: 51 83 ? ? ? ? ? ? 56 57 75 ? E8 ? ? ? ? 5F 5E 59 C3 68

; Host_Status_f (new swds.dll)
SIG: 55 8B ? 81 ? ? ? ? ? A1 ? ? ? ? 33 ? 89 ? ? 53 56 57 BF ? ? ? ? C7

; Host_Status_f (old swds.dll)
SIG: 55 8B ? 81 ? ? ? ? ? A1 ? ? ? ? 53 56 57 BF ? ? ? ? 33 ? 8B ? 3B ? 89 ? ? 89 ? ? 89 ? ? 89 ? ? 89 ? ? C7

; Host_Status_f (rehlds swds.dll)
SIG: 55 8B ? 83 ? ? 83 ? ? 53 56 57 33 ? C7 ? ? ? ? ? ? ? 83 ? ? ? ? ? ? BB ? ? ? ? C7

; Host_Status_Formatted_f (new swds.dll)
SIG: 55 8B ? 81 ? ? ? ? ? A1 ? ? ? ? 33 ? 89 ? ? 53 56 57 BF ? ? ? ? 33 ? 89

; Host_Status_Formatted_f (old swds.dll)
SIG: 55 8B ? 81 ? ? ? ? ? A1 ? ? ? ? 53 56 57 BF ? ? ? ? 33 ? 8B ? 3B ? 89 ? ? 89 ? ? 75 ? 39

; Host_Status_Formatted_f (rehlds swds.dll)
SIG: 55 8B ? 83 ? ? 81 ? ? ? ? ? A1 ? ? ? ? 33 ? 89 ? ? ? ? ? ? 53 56 57 33 ? 33 ? 83

///////////////////////////////////////// Addresses ////////////////////////////////////////////////////////////////////////

; Custom: Patch the process of auto attaching a scope to FG42    during PlayerSpawn
SIG: ? 75 ? 8B ? ? 50 E8 ? ? ? ? 83 ? ? 50 E8 ? ? ? ? 83 ? ? 89 ? ? 83 ? ? ? 74 ? 8B ? ? 8B ? ? ? ? ? 83 ? ? 8B ? ? 89 ? ? ? ? ? 8B ? ? 8B ? 8B ? ? FF ? ? ? ? ? E9 ? ? ? ? 83 ? ? ? 75 ? 68

; Custom: Patch the process of auto attaching a scope to Enfield during PlayerSpawn
SIG: ? 75 ? 8B ? ? 50 E8 ? ? ? ? 83 ? ? 50 E8 ? ? ? ? 83 ? ? 89 ? ? 83 ? ? ? 74 ? 8B ? ? 8B ? ? ? ? ? 83 ? ? 8B ? ? 89 ? ? ? ? ? 8B ? ? 8B ? 8B ? ? FF ? ? ? ? ? EB ? 83 ? ? ? 7D ? 8B ? ? 50 E8

///////////////////////////////////////// Bytes ////////////////////////////////////////////////////////////////////////

; Custom: Original FG42 byte                (pev_playerclass == ...)
SIG: 10

; Custom: FG42 byte to use when patching    (pev_playerclass == ...)
SIG: FF

; Custom: Original Enfield byte             (pev_playerclass == ...)
SIG: 17

; Custom: Enfield byte to use when patching (pev_playerclass == ...)
SIG: FF

///////////////////////////////////////// Settings ////////////////////////////////////////////////////////////////////////

; Minimum Engine '::edict_s* ::client_s::m_pPlayerEntity' offset that can be currently working (including this value itself)
OFFSDEC: 16384

; Maximum Engine '::edict_s* ::client_s::m_pPlayerEntity' offset that can be currently working (up to, not incl.)
OFFSDEC: 65535

///////////////////////////////////////// Offsets (main) ////////////////////////////////////////////////////////////////////////

; '::entvars_s*' offset (pev offs)
OFFSDEC: 4

///////////////////////////////////////// Offsets (game rules) ////////////////////////////////////////////////////////////////////////

; Allies Are British      (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAlliesAreBrit)
OFFSDEC: 388

; Allies Are Paratroopers (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAlliesArePara)
OFFSDEC: 386

; Axis Are Paratroopers   (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAxisArePara)
OFFSDEC: 387

; Allies Infinite Lives   (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAlliesInfiniteLives)
OFFSDEC: 384

; Axis Infinite Lives     (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAxisInfiniteLives)
OFFSDEC: 385

; Allies Respawn Factor   (float ::CDoDTeamPlay::gameplay_rules_t::m_fAlliesRespawnFactor)
OFFSDEC: 424

; Axis Respawn Factor     (float ::CDoDTeamPlay::gameplay_rules_t::m_fAxisRespawnFactor)
OFFSDEC: 428

///////////////////////////////////////// Offsets (weapons/ items) ////////////////////////////////////////////////////////////////////////

; Weapon Has Scope   (int ::CBasePlayerWeapon::m_iWeaponState)
OFFSDEC: 460

; Weapon Index       (int ::CBasePlayerItem::m_iId)
OFFSDEC: 364

; Apply Weapon Scope (void ::CBasePlayerItem::Deploy() @ [Virtual Index #68])
OFFSDEC: 272

///////////////////////////////////////// Offsets (entities) ////////////////////////////////////////////////////////////////////////

; Entity Think Function       (void* ::CBaseEntity::m_pfnThink::__pfn)
OFFSHEX: A0

; Entity Think Function Delta (int ::CBaseEntity::m_pfnThink::__delta)
OFFSHEX: A4

///////////////////////////////////////// Offsets (players) ////////////////////////////////////////////////////////////////////////

; Player Next Class                  (int ::CBasePlayer::m_iNextClass)
OFFSDEC: 1468

; Player Using Random Class          (bool ::CBasePlayer::m_bIsRandomClass)
OFFSDEC: 1472

; Player Recently Changed Their Team (int ::CBasePlayer::m_ilastteam)
OFFSDEC: 1424

; Player Active Item                 (::CBasePlayerItem* ::CBasePlayer::m_pActiveItem)
OFFSDEC: 1112

; Player Respawn Frames
OFFSDEC: 1064                        (float ::CBasePlayer::m_iRespawnFrames)

; Player Frame Rate
OFFSDEC: 332                         (float ::CBasePlayer::m_flFrameRate)

///////
[LINUX]
///////

///////////////////////////////////////// Signatures (__thiscall funcs.) ////////////////////////////////////////////////////////////////////////

; CDoDTeamPlay::PlayerSpawn
_ZN12CDoDTeamPlay11PlayerSpawnEP11CBasePlayer

; CBasePlayer::GiveNamedItem
_ZN11CBasePlayer13GiveNamedItemEPKc

; CBasePlayer::DropPlayerItem
_ZN11CBasePlayer14DropPlayerItemEPcb

; CBasePlayer::GiveAmmo
_ZN11CBasePlayer8GiveAmmoEiPKci

; CDoDTeamPlay::SetWaveTime
_ZN12CDoDTeamPlay11setWaveTimeEif

; CDoDTeamPlay::GetWaveTime
_ZN12CDoDTeamPlay11getWaveTimeEi

; CBasePlayer::RemovePlayerItem
_ZN11CBasePlayer16RemovePlayerItemEP15CBasePlayerItem

; CBasePlayer::AddPlayerItem
_ZN11CBasePlayer13AddPlayerItemEP15CBasePlayerItem

; CBasePlayer::RemoveAllItems
_ZN11CBasePlayer14RemoveAllItemsEi

; CBaseAnimating::SetBodygroup
_ZN14CBaseAnimating12SetBodygroupEii

; CBasePlayerItem::DestroyItem
_ZN15CBasePlayerItem11DestroyItemEv

; CBaseEntity::SUB_Remove
_ZN11CBaseEntity10SUB_RemoveEv

; CWeaponBox::PackWeapon
_ZN10CWeaponBox10PackWeaponEP15CBasePlayerItem

; CWeaponBox::Kill
_ZN10CWeaponBox4KillEv

; CWeaponBox::ActivateThink
_ZN10CWeaponBox13ActivateThinkEv

; CDoDTeamPlay::ChangePlayerTeam
_ZN12CDoDTeamPlay16ChangePlayerTeamEP11CBasePlayeriii

; CDoDTeamPlay::ChooseRandomClass
_ZN12CDoDTeamPlay17ChooseRandomClassEP11CBasePlayer

///////////////////////////////////////// Signatures (__cdecl funcs.) ////////////////////////////////////////////////////////////////////////

; CBaseEntity::Create
_ZN11CBaseEntity6CreateEPcRK6VectorS3_P7edict_s

; InstallGameRules
_Z16InstallGameRulesv

; UTIL_Remove
_Z11UTIL_RemoveP11CBaseEntity

; CREATE_NAMED_ENTITY
_Z19CREATE_NAMED_ENTITYj

; SV_CalcPing (new engine_i486.so)
SV_CalcPing

; SV_CalcPing (old engine_i486.so)
SV_CalcPing

; SV_CalcPing (rehlds engine_i486.so)
_Z11SV_CalcPingP8client_s

; Host_Ping_f (new swds.dll)
Host_Ping_f

; Host_Ping_f (old swds.dll)
Host_Ping_f

; Host_Ping_f (rehlds swds.dll)
_Z11Host_Ping_fv

; Host_Status_f (new swds.dll)
Host_Status_f

; Host_Status_f (old swds.dll)
Host_Status_f

; Host_Status_f (rehlds swds.dll)
_Z13Host_Status_fv

; Host_Status_Formatted_f (new swds.dll)
Host_Status_Formatted_f

; Host_Status_Formatted_f (old swds.dll)
Host_Status_Formatted_f

; Host_Status_Formatted_f (rehlds swds.dll)
_Z23Host_Status_Formatted_fv

///////////////////////////////////////// Signatures (Linux Only) ////////////////////////////////////////////////////////////////////////

; MSG_WriteByte (new swds.dll)
MSG_WriteByte

; MSG_WriteByte (old swds.dll)
MSG_WriteByte

; MSG_WriteByte (rehlds swds.dll)
_Z13MSG_WriteByteP9sizebuf_si

; MSG_WriteBits (new swds.dll)
MSG_WriteBits

; MSG_WriteBits (old swds.dll)
MSG_WriteBits

; MSG_WriteBits (rehlds swds.dll)
_Z13MSG_WriteBitsji

; SV_EmitPings (new swds.dll)
SV_EmitPings

; SV_EmitPings (old swds.dll)
SV_EmitPings

; SV_EmitPings (rehlds swds.dll)
_Z21SV_EmitPings_internalP8client_sP9sizebuf_s

///////////////////////////////////////// Addresses ////////////////////////////////////////////////////////////////////////

; Custom: Patch the process of auto attaching a scope to FG42    during PlayerSpawn
SIG: ? 0F ? ? ? ? ? 85 ? 0F ? ? ? ? ? 83 ? ? 89 ? ? ? 8B ? ? ? ? ? 85 ? 0F ? ? ? ? ? 8B ? ? 85 ? 0F ? ? ? ? ? 8B ? 83 ? ? ? ? ? ? 46 89 ? ? ? 89 ? ? FF ? ? ? ? ? 8B ? ? ? 41 E9

; Custom: Patch the process of auto attaching a scope to Enfield during PlayerSpawn
SIG: ? 0F ? ? ? ? ? EB ? 90 ? ? ? ? B9 ? ? ? ? 89 ? ? ? ? ? 8B ? ? ? ? ? E9 ? ? ? ? 66 ? BA ? ? ? ? 89 ? ? ? ? ? 8B ? ? ? ? ? E9 ? ? ? ? 8B ? ? ? ? ? 85 ? 0F ? ? ? ? ? 31 ? 8D

///////////////////////////////////////// Bytes ////////////////////////////////////////////////////////////////////////

; Custom: Original FG42 byte                (pev_playerclass == ...)
SIG: 10

; Custom: FG42 byte to use when patching    (pev_playerclass == ...)
SIG: FF

; Custom: Original Enfield byte             (pev_playerclass == ...)
SIG: 17

; Custom: Enfield byte to use when patching (pev_playerclass == ...)
SIG: FF

///////////////////////////////////////// Settings ////////////////////////////////////////////////////////////////////////

; Minimum Engine '::edict_s* ::client_s::m_pPlayerEntity' offset that can be currently working (including this value itself)
OFFSDEC: 16384

; Maximum Engine '::edict_s* ::client_s::m_pPlayerEntity' offset that can be currently working (up to, not incl.)
OFFSDEC: 65535

///////////////////////////////////////// Offsets (main) ////////////////////////////////////////////////////////////////////////

; '::entvars_s*' offset (pev offs)
OFFSDEC: 4

///////////////////////////////////////// Offsets (game rules) ////////////////////////////////////////////////////////////////////////

; Allies Are British      (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAlliesAreBrit)
OFFSDEC: 388

; Allies Are Paratroopers (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAlliesArePara)
OFFSDEC: 386

; Axis Are Paratroopers   (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAxisArePara)
OFFSDEC: 387

; Allies Infinite Lives   (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAlliesInfiniteLives)
OFFSDEC: 384

; Axis Infinite Lives     (bool ::CDoDTeamPlay::gameplay_rules_t::m_bAxisInfiniteLives)
OFFSDEC: 385

; Allies Respawn Factor   (float ::CDoDTeamPlay::gameplay_rules_t::m_fAlliesRespawnFactor)
OFFSDEC: 424

; Axis Respawn Factor     (float ::CDoDTeamPlay::gameplay_rules_t::m_fAxisRespawnFactor)
OFFSDEC: 428

///////////////////////////////////////// Offsets (weapons/ items) ////////////////////////////////////////////////////////////////////////

; Weapon Has Scope   (int ::CBasePlayerWeapon::m_iWeaponState)
OFFSDEC: 476

; Weapon Index       (int ::CBasePlayerItem::m_iId)
OFFSDEC: 380

; Apply Weapon Scope (void ::CBasePlayerItem::Deploy() @ [Virtual Index #68])
OFFSDEC: 272

///////////////////////////////////////// Offsets (entities) ////////////////////////////////////////////////////////////////////////

; Entity Think Function       (void* ::CBaseEntity::m_pfnThink::__pfn)
OFFSHEX: A0

; Entity Think Function Delta (int ::CBaseEntity::m_pfnThink::__delta)
OFFSHEX: A4

///////////////////////////////////////// Offsets (players) ////////////////////////////////////////////////////////////////////////

; Player Next Class                  (int ::CBasePlayer::m_iNextClass)
OFFSDEC: 1488

; Player Using Random Class          (bool ::CBasePlayer::m_bIsRandomClass)
OFFSHEX: 5D4

; Player Recently Changed Their Team (int ::CBasePlayer::m_ilastteam)
OFFSHEX: 5A4

; Player Active Item                 (::CBasePlayerItem* ::CBasePlayer::m_pActiveItem)
OFFSDEC: 1132

; Player Respawn Frames
OFFSDEC: 1084                        (float ::CBasePlayer::m_iRespawnFrames)

; Player Frame Rate
OFFSDEC: 352                         (float ::CBasePlayer::m_flFrameRate)
