
;
; ---------
; DoD Hacks
; ---------
; Always keep 'dod_hacks_knives.amxx' below
; 'dod_hacks_nademanager.amxx', as
; 'dod_hacks_knives.amxx' is erasing
; '::CBasePlayerItem* ::CBasePlayer::m_pActiveItem'
; during 'void ::CBasePlayer::Killed()' and
; 'dod_hacks_nademanager.amxx' requires
; '::CBasePlayerItem* ::CBasePlayer::m_pActiveItem'
; when 'void ::CBasePlayer::Killed()' is being
; called by the game.
;

dod_hacks_death.amxx
dod_hacks_killer.amxx
dod_hacks_weapons.amxx
dod_hacks_respawn.amxx
dod_hacks_automedic.amxx
dod_hacks_keyvalues.amxx
dod_hacks_nademanager.amxx
dod_hacks_headshot.amxx
dod_hacks_adverts.amxx
dod_hacks_mapchooser.amxx
dod_hacks_parachute.amxx
dod_hacks_knives.amxx
dod_hacks_balancer.amxx
dod_hacks_pingfaker.amxx
dod_hacks_hostname.amxx
dod_hacks_crash.amxx
dod_hacks_tracers.amxx
dod_hacks_deploy.amxx
dod_hacks_suicide.amxx
dod_hacks_lighting.amxx
dod_hacks_rank.amxx
dod_hacks_round.amxx
dod_hacks_bots.amxx
dod_hacks_trails.amxx
dod_hacks_ammo.amxx
dod_hacks_stats.amxx
dod_hacks_scrollmsg.amxx
